import { useCallback, useMemo, useState, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { AnimatePresence, MotionConfig, motion, type Variants } from 'framer-motion'
import {
  ArrowRight,
  ArrowUpRight,
  BadgeDollarSign,
  Bus,
  Compass,
  Headset,
  Map as MapIcon,
  ShieldCheck,
  Users,
  Waves,
} from 'lucide-react'
import Footer from '../components/Footer'
import SEO, { buildBreadcrumbSchema, buildOrganizationSchema } from '../components/SEO'
import BackToHelpCentre from '../components/support/BackToHelpCentre'
import ImageLightbox, { type GalleryImage } from '../components/gallery/ImageLightbox'
import SwipeCarousel from '../components/SwipeCarousel'
import PartnersSection from '../components/PartnersSection'
import WhyBookSection from '../components/WhyBookSection'
import useMediaQuery from '../hooks/useMediaQuery'
import './AboutUsPage.css'

import hero1 from '../assets/about/hero-1.webp'
import hero2 from '../assets/about/hero-2.webp'
import hero3 from '../assets/about/hero-3.webp'
import hero4 from '../assets/about/hero-4.webp'
import story1 from '../assets/about/story-1.webp'
import story2 from '../assets/about/story-2.webp'
import story3 from '../assets/about/story-3.webp'
import story4 from '../assets/about/story-4.webp'
import categoryTour from '../assets/about/category-tour.webp'
import categoryActivity from '../assets/about/category-activity.webp'
import categoryTransport from '../assets/about/category-transport.webp'
import categoryAkosombo from '../assets/about/category-akosombo.webp'

/*
 * Widths/heights mirror the committed files in src/assets/about (generated by
 * scripts/generate-about-images.cjs). They are declared as attributes so the
 * browser reserves space before pixels arrive — no layout shift.
 */
const HERO_IMAGES = [
  { src: hero1, width: 643, height: 900 },
  { src: hero2, width: 1350, height: 900 },
  { src: hero3, width: 1350, height: 900 },
  { src: hero4, width: 600, height: 900 },
]

const STORY_IMAGES = [
  { src: story1, key: 'imageStory1', width: 690, height: 785, tall: true },
  { src: story2, key: 'imageStory2', width: 720, height: 480, tall: false },
  { src: story3, key: 'imageStory3', width: 720, height: 479, tall: false },
  { src: story4, key: 'imageStory4', width: 720, height: 480, tall: true },
]

const CATEGORY_IMAGES = [
  { src: categoryTour, key: 'categoryTour', width: 1040, height: 693, Icon: Compass, area: 'hero' },
  { src: categoryActivity, key: 'categoryActivity', width: 900, height: 587, Icon: MapIcon, area: 'top-left' },
  { src: categoryTransport, key: 'categoryTransport', width: 900, height: 600, Icon: Bus, area: 'top-right' },
  { src: categoryAkosombo, key: 'categoryAkosombo', width: 720, height: 480, Icon: Waves, area: 'wide' },
]

const VALUE_ICONS = [Compass, Users, ShieldCheck, BadgeDollarSign, Headset]

const fadeUp: Variants = {
  hidden: { opacity: 0, y: 26 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: 'easeOut' } },
}

const stagger: Variants = {
  visible: { transition: { staggerChildren: 0.1 } },
}

export default function AboutUsPage() {
  const { t } = useTranslation()
  const isMobile = useMediaQuery('(max-width: 900px)')
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null)

  const gallery = useMemo<GalleryImage[]>(
    () => [
      ...STORY_IMAGES.map((img) => ({
        src: img.src,
        alt: t(`about.${img.key}`),
        width: img.width,
        height: img.height,
      })),
      ...CATEGORY_IMAGES.map((img) => ({
        src: img.src,
        alt: t(`about.${img.key}`),
        width: img.width,
        height: img.height,
      })),
    ],
    [t],
  )

  const openLightbox = useCallback(
    (src: string) => {
      const index = gallery.findIndex((img) => img.src === src)
      if (index !== -1) setLightboxIndex(index)
    },
    [gallery],
  )

  const closeLightbox = useCallback(() => setLightboxIndex(null), [])

  const navigateLightbox = useCallback(
    (delta: number) => {
      setLightboxIndex((index) =>
        index === null ? index : (index + delta + gallery.length) % gallery.length,
      )
    },
    [gallery.length],
  )

  const VALUES = [
    { Icon: VALUE_ICONS[0], title: t('about.value1Title'), text: t('about.value1Text') },
    { Icon: VALUE_ICONS[1], title: t('about.value2Title'), text: t('about.value2Text') },
    { Icon: VALUE_ICONS[2], title: t('about.value3Title'), text: t('about.value3Text') },
    { Icon: VALUE_ICONS[3], title: t('about.value4Title'), text: t('about.value4Text') },
    { Icon: VALUE_ICONS[4], title: t('about.value5Title'), text: t('about.value5Text') },
  ]

  const storyTile = (img: (typeof STORY_IMAGES)[number]): ReactNode => (
    <button
      key={img.key}
      type="button"
      className={`about-tile about-story-tile${img.tall ? ' about-story-tile--tall' : ''}`}
      onClick={() => openLightbox(img.src)}
    >
      <img
        src={img.src}
        alt={t(`about.${img.key}`)}
        width={img.width}
        height={img.height}
        /* Off-screen carousel slides are clipped by the track's overflow, so
           native lazy-loading never fires for them — load eagerly on touch
           layouts where the carousel is used. */
        loading={isMobile ? 'eager' : 'lazy'}
        decoding="async"
      />
    </button>
  )

  const storySlides = STORY_IMAGES.map(storyTile)

  const storyBadge = (
    <div className="about-story-badge about-glass">
      <span className="about-story-badge-icon" aria-hidden="true">
        <ShieldCheck size={18} />
      </span>
      <span className="about-story-badge-copy">
        <span className="about-story-badge-title">{t('about.badgeTitle')}</span>
        <span className="about-story-badge-text">{t('about.badgeText')}</span>
      </span>
    </div>
  )

  const categoryTile = (img: (typeof CATEGORY_IMAGES)[number]): ReactNode => {
    const Icon = img.Icon
    return (
      <button
        key={img.key}
        type="button"
        className={`about-tile about-category-tile about-category-tile--${img.area}`}
        aria-label={t(`about.${img.key}`)}
        onClick={() => openLightbox(img.src)}
      >
        <img
          src={img.src}
          alt=""
          aria-hidden="true"
          width={img.width}
          height={img.height}
          loading={isMobile ? 'eager' : 'lazy'}
          decoding="async"
        />
        <span className="about-category-glow" aria-hidden="true" />
        <span className="about-category-label">
          <Icon size={15} aria-hidden="true" />
          {t(`about.${img.key}`)}
          <ArrowUpRight className="about-category-label-arrow" size={15} aria-hidden="true" />
        </span>
      </button>
    )
  }

  const categoryTiles = CATEGORY_IMAGES.map(categoryTile)

  const valueCards = VALUES.map((value) => (
    <div key={value.title} className="about-value-card about-glass">
      <span className="about-value-icon" aria-hidden="true">
        <value.Icon size={20} />
      </span>
      <h3 className="about-value-title">{value.title}</h3>
      <p className="about-value-text">{value.text}</p>
    </div>
  ))

  return (
    <MotionConfig reducedMotion="user">
      <div className="about-page">
        <SEO
          title={t('about.pageTitle')}
          description="Learn about Expedition-Go Tours — Ghana's premier tour platform. We connect travellers with authentic local experiences and partner with the world's leading travel brands. Meet our team, mission and why travellers book with us."
          keywords="Expedition-Go Tours, about us, Ghana tour company, Ghana travel platform, local tours Ghana, authentic experiences Ghana, Ghana tourism company, trusted travel partners Ghana, why book with us"
          jsonLd={[
            buildBreadcrumbSchema([
              { name: 'Home', url: 'https://www.expeditiongotours.com/' },
              { name: 'About Us', url: 'https://www.expeditiongotours.com/about-us' },
            ]),
            buildOrganizationSchema(),
          ]}
        />

        {/* ===== Hero — moving photo strip behind a light glass panel ===== */}
        <section className="about-hero">
          <div className="about-hero-bg" aria-hidden="true">
            <div className="about-hero-track">
              {[...HERO_IMAGES, ...HERO_IMAGES].map((img, i) => (
                <img
                  key={i}
                  src={img.src}
                  alt=""
                  width={img.width}
                  height={img.height}
                  loading={i < HERO_IMAGES.length ? 'eager' : 'lazy'}
                  fetchPriority={i === 0 ? 'high' : undefined}
                  decoding="async"
                />
              ))}
            </div>
            <div className="about-hero-veil" />
          </div>

          <span className="about-hero-orb about-hero-orb--a" aria-hidden="true" />
          <span className="about-hero-orb about-hero-orb--b" aria-hidden="true" />

          <motion.div
            className="about-hero-panel about-glass"
            initial="hidden"
            animate="visible"
            variants={fadeUp}
          >
            <BackToHelpCentre requireOrigin className="about-hero-back" />
            <p className="about-hero-eyebrow">
              <span className="about-hero-eyebrow-dot" aria-hidden="true" />
              {t('about.heroLabel')}
            </p>
            <h1 className="about-hero-title">{t('about.heroTitle')}</h1>
            <p className="about-hero-subtitle">{t('company.aboutUsSubtitle')}</p>
            <div className="about-hero-actions">
              <Link to="/tours" className="about-btn about-btn--primary">
                {t('about.ctaBrowse')}
                <ArrowRight size={16} aria-hidden="true" />
              </Link>
              <Link to="/contact-us" className="about-btn about-btn--outline">
                {t('about.ctaContact')}
              </Link>
            </div>
          </motion.div>
        </section>

        <div className="about-container">
          {/* ===== Our Story — asymmetric split + staggered mosaic ===== */}
          <motion.section
            className="about-story"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-80px' }}
            variants={stagger}
          >
            <motion.div className="about-story-text" variants={fadeUp}>
              <p className="about-eyebrow">{t('about.storyLabel')}</p>
              <h2 className="about-heading">{t('about.storyTitle')}</h2>
              <p className="about-body">{t('about.storyText1')}</p>
              <p className="about-body">{t('about.storyText2')}</p>
            </motion.div>

            {isMobile ? (
              <>
                <SwipeCarousel label={t('about.storyLabel')} slides={storySlides} />
                {storyBadge}
              </>
            ) : (
              <motion.div className="about-story-mosaic" variants={stagger}>
                <div className="about-story-mosaic-col">
                  {storySlides[0]}
                  {storySlides[2]}
                </div>
                <div className="about-story-mosaic-col about-story-mosaic-col--offset">
                  {storySlides[1]}
                  {storySlides[3]}
                </div>
                <motion.div variants={fadeUp} className="about-story-badge-slot">
                  {storyBadge}
                </motion.div>
              </motion.div>
            )}
          </motion.section>

          {/* ===== What you can book — labeled bento gallery ===== */}
          <motion.section
            className="about-categories"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-80px' }}
            variants={stagger}
          >
            <motion.div className="about-categories-head" variants={fadeUp}>
              <p className="about-eyebrow">{t('about.categoriesLabel')}</p>
              <h2 className="about-heading">{t('about.calloutHeading')}</h2>
              <p className="about-body">{t('about.calloutBody')}</p>
            </motion.div>

            {isMobile ? (
              <SwipeCarousel label={t('about.categoriesLabel')} slides={categoryTiles} />
            ) : (
              <div className="about-category-grid">{categoryTiles}</div>
            )}
          </motion.section>

          {/* ===== Values ===== */}
          <motion.section
            className="about-values"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-80px' }}
            variants={stagger}
          >
            <motion.div className="about-values-head" variants={fadeUp}>
              <p className="about-eyebrow">{t('about.valuesLabel')}</p>
              <h2 className="about-heading">{t('about.valuesTitle')}</h2>
            </motion.div>

            {isMobile ? (
              <SwipeCarousel label={t('about.valuesTitle')} slides={valueCards} />
            ) : (
              <div className="about-values-grid">{valueCards}</div>
            )}
          </motion.section>

          {/* ===== Partners — trust logos (moved from the home page) ===== */}
          <motion.div
            className="about-partners"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-80px' }}
            variants={fadeUp}
          >
            <PartnersSection />
          </motion.div>

          {/* ===== Why travellers book with us (moved from the home page) ===== */}
          <motion.div
            className="about-whybook"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-80px' }}
            variants={fadeUp}
          >
            <WhyBookSection />
          </motion.div>

          {/* ===== CTA ===== */}
          <motion.section
            className="about-cta"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-60px' }}
            variants={fadeUp}
          >
            <span className="about-cta-orb about-cta-orb--a" aria-hidden="true" />
            <span className="about-cta-orb about-cta-orb--b" aria-hidden="true" />
            <div className="about-cta-content">
              <h2 className="about-cta-title">{t('about.ctaTitle')}</h2>
              <div className="about-cta-actions">
                <Link to="/tours" className="about-btn about-btn--primary">
                  {t('about.ctaBrowse')}
                  <ArrowRight size={16} aria-hidden="true" />
                </Link>
                <Link to="/contact-us" className="about-btn about-btn--outline">
                  {t('about.ctaContact')}
                </Link>
              </div>
            </div>
          </motion.section>
        </div>

        <AnimatePresence>
          {lightboxIndex !== null && (
            <ImageLightbox
              images={gallery}
              index={lightboxIndex}
              onClose={closeLightbox}
              onNavigate={navigateLightbox}
            />
          )}
        </AnimatePresence>

        <Footer />
      </div>
    </MotionConfig>
  )
}
