export interface Tour {
  title: string
  category: string
  duration: string
  features: string
  price: string
  rating: string
  reviews: number
  location: string
  image: string
  discount?: string
}

const recommendedTours: Tour[] = [
  {
    title: 'From Accra: Cape Coast, Elmina Castle & Kakum Park Day Tour',
    category: 'Accra · Day trip',
    duration: '9 hours',
    features: 'Pickup available · Skip the line',
    price: '$127',
    rating: '4.8',
    reviews: 21,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1612878010854-1250dfc1a109?w=400&q=80',
  },
  {
    title: 'Kakum National Park Canopy Walk & Rainforest Adventure',
    category: 'Central · Adventure',
    duration: '8 hours',
    features: 'Guide included · Lunch included',
    price: '$84',
    rating: '4.9',
    reviews: 34,
    location: 'Central Region, Ghana',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&q=80',
  },
  {
    title: 'Cape Coast Castle & Slave River Tour with Transporation',
    category: 'Cape Coast · History',
    duration: '6 hours',
    features: 'Pickup available · Entry fees included',
    price: '$57',
    rating: '4.7',
    reviews: 45,
    location: 'Cape Coast, Ghana',
    image: 'https://images.unsplash.com/photo-1590868169155-f1a0c43106ef?w=400&q=80',
  },
  {
    title: 'Accra City Tour: Markets, Museums & Local Cuisine',
    category: 'Accra · City tour',
    duration: '5 hours',
    features: 'Guide included · Tastings included',
    price: '$46',
    rating: '4.6',
    reviews: 28,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=400&q=80',
  },
  {
    title: 'Mole National Park Wildlife Safari & Lodge Stay',
    category: 'Northern · Safari',
    duration: '3 days',
    features: 'Accommodation · All meals · Guide',
    price: '$171',
    rating: '4.9',
    reviews: 17,
    location: 'Northern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400&q=80',
  },
  {
    title: 'Boti Falls Waterfall Hike & Eastern Region Tour',
    category: 'Eastern · Nature',
    duration: '7 hours',
    features: 'Hiking gear · Guide · Lunch',
    price: '$38',
    rating: '4.5',
    reviews: 13,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1578926378480-5e050966f37e?w=400&q=80',
  },
  {
    title: 'Jamestown Walking Tour: History, Art & Street Food',
    category: 'Accra · Walking tour',
    duration: '3 hours',
    features: 'Local guide · Food included',
    price: '$26',
    rating: '4.6',
    reviews: 31,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1591843336309-cbfcbad9b118?w=400&q=80',
  },
  {
    title: 'Lake Volta Sunset Cruise & Island Exploration',
    category: 'Volta · Cruise',
    duration: '6 hours',
    features: 'Drinks included · Return transfer',
    price: '$62',
    rating: '4.7',
    reviews: 19,
    location: 'Volta Region, Ghana',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
  },
  {
    title: 'Elmina Fishing Village & Dutch Heritage Tour',
    category: 'Elmina · Cultural',
    duration: '5 hours',
    features: 'Local guide · Entry fees',
    price: '$43',
    rating: '4.5',
    reviews: 22,
    location: 'Elmina, Ghana',
    image: 'https://images.unsplash.com/photo-1590868169155-f1a0c43106ef?w=400&q=80',
  },
  {
    title: 'Shai Hills Nature Reserve & Rock Climbing Day Trip',
    category: 'Accra · Adventure',
    duration: '6 hours',
    features: 'Climbing gear · Guide · Lunch',
    price: '$52',
    rating: '4.4',
    reviews: 16,
    location: 'Greater Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&q=80',
  },
]

export interface Destination {
  title: string
  tours: string
  image: string
}

const destinations: Destination[] = [
  {
    title: 'Accra',
    tours: '120+ Tours',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80',
  },
  {
    title: 'Cape Coast',
    tours: '80+ Tours',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80',
  },
  {
    title: 'Kakum National Park',
    tours: '45+ Tours',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
  },
  {
    title: 'Kumasi',
    tours: '70+ Tours',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&q=80',
  },
  {
    title: 'Elmina',
    tours: '55+ Tours',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=600&q=80',
  },
  {
    title: 'Mole National Park',
    tours: '30+ Tours',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=600&q=80',
  },
  {
    title: 'Wli Waterfalls',
    tours: '25+ Tours',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=600&q=80',
  },
  {
    title: 'Ada Foah',
    tours: '30+ Tours',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
  },
  {
    title: 'Busua Beach',
    tours: '22+ Tours',
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=600&q=80',
  },
  {
    title: 'Shai Hills Reserve',
    tours: '20+ Tours',
    image: 'https://images.unsplash.com/photo-1472396961693-142e6e269027?w=600&q=80',
  },
]

const dayTours: Tour[] = [
  {
    title: 'Full Day Accra City & Cultural Experience',
    category: 'Accra · Day trip',
    duration: 'Full day',
    features: 'Guide included · Lunch included',
    price: '$89',
    rating: '4.7',
    reviews: 56,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&q=80',
  },
  {
    title: 'Cape Coast Castles & Heritage Day Tour',
    category: 'Cape Coast · History',
    duration: '8 hours',
    features: 'Pickup available · Entry fees included',
    price: '$72',
    rating: '4.8',
    reviews: 43,
    location: 'Cape Coast, Ghana',
    image: 'https://images.unsplash.com/photo-1590868169155-f1a0c43106ef?w=400&q=80',
  },
  {
    title: 'Kakum Canopy Walk & Rainforest Hike',
    category: 'Central · Adventure',
    duration: '6 hours',
    features: 'Guide included · Safety gear',
    price: '$65',
    rating: '4.9',
    reviews: 38,
    location: 'Kakum, Ghana',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&q=80',
  },
  {
    title: 'Boti Falls Hike & Eastern Region Day Trip',
    category: 'Eastern · Nature',
    duration: 'Full day',
    features: 'Hiking gear · Guide · Lunch',
    price: '$55',
    rating: '4.6',
    reviews: 24,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1578926378480-5e050966f37e?w=400&q=80',
  },
  {
    title: 'Lake Volta Sunset Cruise Day Tour',
    category: 'Volta · Cruise',
    duration: '6 hours',
    features: 'Drinks included · Return transfer',
    price: '$78',
    rating: '4.7',
    reviews: 31,
    location: 'Volta Region, Ghana',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
  },
  {
    title: 'Jamestown Walking & Street Food Tour',
    category: 'Accra · Food',
    duration: 'Half day',
    features: 'Local guide · Tastings included',
    price: '$42',
    rating: '4.6',
    reviews: 47,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1591843336309-cbfcbad9b118?w=400&q=80',
  },
  {
    title: 'Mole National Park Safari Day Experience',
    category: 'Northern · Safari',
    duration: 'Full day',
    features: 'Park fees · Guide · Lunch',
    price: '$95',
    rating: '4.9',
    reviews: 22,
    location: 'Northern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400&q=80',
  },
  {
    title: 'Shai Hills Rock Climbing & Nature Walk',
    category: 'Accra · Adventure',
    duration: '6 hours',
    features: 'Climbing gear · Guide · Lunch',
    price: '$58',
    rating: '4.5',
    reviews: 19,
    location: 'Greater Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&q=80',
  },
  {
    title: 'Elmina Fishing Village & Dutch Heritage',
    category: 'Elmina · Cultural',
    duration: '5 hours',
    features: 'Local guide · Entry fees',
    price: '$48',
    rating: '4.5',
    reviews: 28,
    location: 'Elmina, Ghana',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&q=80',
  },
  {
    title: 'Ada Foah Beach Escape & River Cruise',
    category: 'Greater Accra · Leisure',
    duration: 'Full day',
    features: 'Lunch included · Beach access',
    price: '$68',
    rating: '4.6',
    reviews: 35,
    location: 'Ada Foah, Ghana',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
  },
]

export interface MultiDayTour {
  title: string
  days: string
  accommodation: string
  highlights: string
  price: string
  rating: string
  reviews: number
  location: string
  image: string
}

const multiDayTours: MultiDayTour[] = [
  {
    title: 'Northern Ghana Safari & Cultural Expedition',
    days: '5 days',
    accommodation: 'Lodge & Camping',
    highlights: 'Mole Park · Larabanga Mosque · Paga',
    price: '$520',
    rating: '4.9',
    reviews: 28,
    location: 'Northern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=400&q=80',
  },
  {
    title: 'Coastal Heritage & Beaches Journey',
    days: '4 days',
    accommodation: 'Beach Resort',
    highlights: 'Cape Coast · Elmina · Busua Beach',
    price: '$440',
    rating: '4.8',
    reviews: 35,
    location: 'Central Region, Ghana',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
  },
  {
    title: 'Ashanti Kingdom & Kumasi Explorer',
    days: '3 days',
    accommodation: 'City Hotel',
    highlights: 'Manhyia Palace · Kejetia Market · Craft villages',
    price: '$310',
    rating: '4.7',
    reviews: 22,
    location: 'Kumasi, Ghana',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&q=80',
  },
  {
    title: 'Volta Region Waterfalls & Nature Trek',
    days: '4 days',
    accommodation: 'Eco Lodge',
    highlights: 'Wli Falls · Lake Volta · Tafi Atome',
    price: '$395',
    rating: '4.8',
    reviews: 19,
    location: 'Volta Region, Ghana',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=400&q=80',
  },
  {
    title: 'Greater Accra City & Beach Getaway',
    days: '3 days',
    accommodation: 'Boutique Hotel',
    highlights: 'Accra tours · Ada Foah · Labadi Beach',
    price: '$280',
    rating: '4.6',
    reviews: 42,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&q=80',
  },
  {
    title: 'Eastern Region Adventure & Waterfalls',
    days: '3 days',
    accommodation: 'Mountain Lodge',
    highlights: 'Boti Falls · Aburi Gardens · Shai Hills',
    price: '$265',
    rating: '4.7',
    reviews: 16,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&q=80',
  },
  {
    title: 'Western Region Rainforest & Beach Combo',
    days: '5 days',
    accommodation: 'Beach Resort',
    highlights: 'Nzulezu · Busua · Rainforest canopy',
    price: '$580',
    rating: '4.8',
    reviews: 25,
    location: 'Western Region, Ghana',
    image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=400&q=80',
  },
  {
    title: 'Ghana Discovery Grand Tour',
    days: '10 days',
    accommodation: 'Mixed (Hotel/Lodge)',
    highlights: 'Full Ghana circuit · All regions',
    price: '$1,150',
    rating: '4.9',
    reviews: 14,
    location: 'Ghana',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=400&q=80',
  },
  {
    title: 'Mole & Savannah Wildlife Safari',
    days: '4 days',
    accommodation: 'Safari Lodge',
    highlights: 'Mole Park · Game drives · Walking safaris',
    price: '$490',
    rating: '4.9',
    reviews: 31,
    location: 'Northern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400&q=80',
  },
  {
    title: 'Central Region Castles & Rainforest',
    days: '3 days',
    accommodation: 'Eco Resort',
    highlights: 'Kakum Park · Cape Coast Castle · Canopy walk',
    price: '$340',
    rating: '4.7',
    reviews: 38,
    location: 'Central Region, Ghana',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&q=80',
  },
]

const topRatedTours: Tour[] = [
  {
    title: 'Kakum Canopy Walk & Rainforest Adventure',
    category: 'Central · Adventure',
    duration: '6 hours',
    features: 'Guide included · Safety gear · Park fees',
    price: '$65',
    rating: '4.9',
    reviews: 320,
    location: 'Kakum, Ghana',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&q=80',
  },
  {
    title: 'Mole National Park Wildlife Safari',
    category: 'Northern · Safari',
    duration: 'Full day',
    features: 'Park fees · Guide · Lunch included',
    price: '$95',
    rating: '4.9',
    reviews: 210,
    location: 'Northern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=400&q=80',
  },
  {
    title: 'Cape Coast Castle & Heritage Tour',
    category: 'Cape Coast · History',
    duration: '6 hours',
    features: 'Pickup available · Entry fees included',
    price: '$57',
    rating: '4.8',
    reviews: 410,
    location: 'Cape Coast, Ghana',
    image: 'https://images.unsplash.com/photo-1590868169155-f1a0c43106ef?w=400&q=80',
  },
  {
    title: 'Full Day Accra City & Cultural Experience',
    category: 'Accra · City tour',
    duration: 'Full day',
    features: 'Guide included · Lunch · Tastings',
    price: '$89',
    rating: '4.8',
    reviews: 260,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&q=80',
  },
  {
    title: 'Aburi Botanical Gardens & Tetteh Quarshie Cocoa Farm',
    category: 'Eastern · Nature',
    duration: '5 hours',
    features: 'Guide included · Transport included',
    price: '$46',
    rating: '4.8',
    reviews: 190,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400&q=80',
  },
  {
    title: 'Elmina Castle & Fishing Village Tour',
    category: 'Elmina · Cultural',
    duration: '5 hours',
    features: 'Local guide · Entry fees · Boat ride',
    price: '$52',
    rating: '4.8',
    reviews: 280,
    location: 'Elmina, Ghana',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&q=80',
  },
  {
    title: 'Wli Waterfalls Hike & Volta Nature Escape',
    category: 'Volta · Nature',
    duration: '6 hours',
    features: 'Hiking gear · Guide · Lunch',
    price: '$55',
    rating: '4.8',
    reviews: 175,
    location: 'Volta Region, Ghana',
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=400&q=80',
  },
  {
    title: 'Kumasi Ashanti Kingdom & Craft Villages',
    category: 'Kumasi · Cultural',
    duration: 'Full day',
    features: 'Guide · Transport · Lunch included',
    price: '$72',
    rating: '4.8',
    reviews: 230,
    location: 'Kumasi, Ghana',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&q=80',
  },
  {
    title: 'Ada Foah Beach Resort Day Pass & Cruise',
    category: 'Greater Accra · Leisure',
    duration: 'Full day',
    features: 'Lunch · Drinks · Pool & beach access',
    price: '$68',
    rating: '4.8',
    reviews: 165,
    location: 'Ada Foah, Ghana',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
  },
  {
    title: 'Jamestown Arts & Street Food Walking Tour',
    category: 'Accra · Food',
    duration: '3 hours',
    features: 'Local guide · Tastings · Art visit',
    price: '$38',
    rating: '4.8',
    reviews: 310,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1591843336309-cbfcbad9b118?w=400&q=80',
  },
]

const sellOutTours: Tour[] = [
  {
    title: 'Cape Coast Castle & Kakum Park Combo',
    category: 'Central · Best seller',
    duration: 'Full day',
    features: 'Pickup · Lunch · Entry fees',
    price: '$97',
    discount: 'Likely to sell out',
    rating: '4.8',
    reviews: 280,
    location: 'Cape Coast, Ghana',
    image: 'https://images.unsplash.com/photo-1590868169155-f1a0c43106ef?w=400&q=80',
  },
  {
    title: 'Kakum Canopy Walk & Rainforest Tour',
    category: 'Central · Adventure',
    duration: '6 hours',
    features: 'Guide · Safety gear · Park fees',
    price: '$65',
    discount: 'Likely to sell out',
    rating: '4.9',
    reviews: 320,
    location: 'Kakum, Ghana',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&q=80',
  },
  {
    title: 'Mole National Park Full Day Safari',
    category: 'Northern · Safari',
    duration: 'Full day',
    features: 'Park fees · Guide · Lunch',
    price: '$95',
    discount: 'Likely to sell out',
    rating: '4.9',
    reviews: 210,
    location: 'Northern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=400&q=80',
  },
  {
    title: 'Boti Falls & Eastern Region Day Trip',
    category: 'Eastern · Nature',
    duration: 'Full day',
    features: 'Hiking gear · Guide · Lunch',
    price: '$55',
    discount: 'Likely to sell out',
    rating: '4.6',
    reviews: 145,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1578926378480-5e050966f37e?w=400&q=80',
  },
  {
    title: 'Jamestown Arts & Street Food Tour',
    category: 'Accra · Food',
    duration: '3 hours',
    features: 'Local guide · Tastings included',
    price: '$38',
    discount: 'Likely to sell out',
    rating: '4.6',
    reviews: 310,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1591843336309-cbfcbad9b118?w=400&q=80',
  },
  {
    title: 'Accra City Tour & Markets Experience',
    category: 'Accra · City tour',
    duration: '6 hours',
    features: 'Guide · Transport · Lunch',
    price: '$72',
    discount: 'Likely to sell out',
    rating: '4.7',
    reviews: 260,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=400&q=80',
  },
  {
    title: 'Elmina Castle & Heritage Walking Tour',
    category: 'Elmina · Cultural',
    duration: '5 hours',
    features: 'Local guide · Entry fees',
    price: '$48',
    discount: 'Likely to sell out',
    rating: '4.7',
    reviews: 230,
    location: 'Elmina, Ghana',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&q=80',
  },
  {
    title: 'Lake Volta Sunset Cruise & Dinner',
    category: 'Volta · Cruise',
    duration: '4 hours',
    features: 'Drinks · Dinner · Return transfer',
    price: '$78',
    discount: 'Likely to sell out',
    rating: '4.7',
    reviews: 185,
    location: 'Volta Region, Ghana',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
  },
  {
    title: 'Aburi Gardens & Cocoa Farm Tour',
    category: 'Eastern · Nature',
    duration: '5 hours',
    features: 'Guide · Transport included',
    price: '$46',
    discount: 'Likely to sell out',
    rating: '4.8',
    reviews: 190,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400&q=80',
  },
  {
    title: 'Ada Foah Beach Resort Day Pass',
    category: 'Greater Accra · Leisure',
    duration: 'Full day',
    features: 'Lunch · Drinks · Beach access',
    price: '$68',
    discount: 'Likely to sell out',
    rating: '4.8',
    reviews: 165,
    location: 'Ada Foah, Ghana',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
  },
]

const lastMinuteDeals: Tour[] = [
  {
    title: 'Kakum Canopy Walk & Rainforest',
    category: 'Central · Flash deal',
    duration: '6 hours',
    features: 'Guide · Safety gear · Park fees',
    price: '$45',
    discount: '-30%',
    rating: '4.9',
    reviews: 320,
    location: 'Kakum, Ghana',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&q=80',
  },
  {
    title: 'Cape Coast Castle & Heritage Tour',
    category: 'Cape Coast · Flash deal',
    duration: '6 hours',
    features: 'Pickup · Entry fees included',
    price: '$40',
    discount: '-30%',
    rating: '4.8',
    reviews: 410,
    location: 'Cape Coast, Ghana',
    image: 'https://images.unsplash.com/photo-1590868169155-f1a0c43106ef?w=400&q=80',
  },
  {
    title: 'Accra City Tour & Cultural Walk',
    category: 'Accra · Flash deal',
    duration: '6 hours',
    features: 'Guide · Lunch · Tastings',
    price: '$62',
    discount: '-30%',
    rating: '4.7',
    reviews: 260,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&q=80',
  },
  {
    title: 'Mole National Park Safari Adventure',
    category: 'Northern · Flash deal',
    duration: 'Full day',
    features: 'Park fees · Guide · Lunch',
    price: '$67',
    discount: '-30%',
    rating: '4.9',
    reviews: 210,
    location: 'Northern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=400&q=80',
  },
  {
    title: 'Elmina Castle & Fishing Village',
    category: 'Elmina · Flash deal',
    duration: '5 hours',
    features: 'Local guide · Entry fees',
    price: '$34',
    discount: '-30%',
    rating: '4.7',
    reviews: 280,
    location: 'Elmina, Ghana',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&q=80',
  },
  {
    title: 'Lake Volta Sunset Cruise',
    category: 'Volta · Flash deal',
    duration: '4 hours',
    features: 'Drinks · Return transfer',
    price: '$55',
    discount: '-30%',
    rating: '4.7',
    reviews: 185,
    location: 'Volta Region, Ghana',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
  },
  {
    title: 'Boti Falls & Eastern Region Tour',
    category: 'Eastern · Flash deal',
    duration: 'Full day',
    features: 'Hiking gear · Guide · Lunch',
    price: '$39',
    discount: '-30%',
    rating: '4.6',
    reviews: 145,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1578926378480-5e050966f37e?w=400&q=80',
  },
  {
    title: 'Jamestown Street Food & Art Tour',
    category: 'Accra · Flash deal',
    duration: '3 hours',
    features: 'Local guide · Tastings',
    price: '$27',
    discount: '-30%',
    rating: '4.6',
    reviews: 310,
    location: 'Accra, Ghana',
    image: 'https://images.unsplash.com/photo-1591843336309-cbfcbad9b118?w=400&q=80',
  },
  {
    title: 'Aburi Gardens & Cocoa Farm',
    category: 'Eastern · Flash deal',
    duration: '5 hours',
    features: 'Guide · Transport',
    price: '$32',
    discount: '-30%',
    rating: '4.8',
    reviews: 190,
    location: 'Eastern Region, Ghana',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400&q=80',
  },
  {
    title: 'Ada Foah Beach Day Pass',
    category: 'Greater Accra · Flash deal',
    duration: 'Full day',
    features: 'Lunch · Drinks · Beach access',
    price: '$48',
    discount: '-30%',
    rating: '4.8',
    reviews: 165,
    location: 'Ada Foah, Ghana',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
  },
]

export interface Review {
  name: string
  avatar: string
  rating: number
  date: string
  text: string
  location: string
}

const reviews: Review[] = [
  {
    name: 'Sarah Mitchell',
    avatar: 'SM',
    rating: 5,
    date: 'March 2026',
    text: 'Incredible Kakum Canopy Walk! Our guide Kwame made everyone feel safe. Delicious local lunch included. Highly recommend!',
    location: 'Accra, Ghana',
  },
  {
    name: 'James Thompson',
    avatar: 'JT',
    rating: 5,
    date: 'February 2026',
    text: 'Deeply moving Cape Coast Castle tour. Our guide explained the history with clarity and respect. A must-do in Ghana.',
    location: 'London, UK',
  },
  {
    name: 'Maria Gonzalez',
    avatar: 'MG',
    rating: 5,
    date: 'January 2026',
    text: 'Mole National Park safari exceeded expectations! Saw elephants and monkeys up close. Comfortable lodge and welcoming staff.',
    location: 'Madrid, Spain',
  },
  {
    name: 'David Chen',
    avatar: 'DC',
    rating: 4,
    date: 'December 2025',
    text: 'Great Accra city tour — markets, museums, and the best jollof rice I\'ve ever had. Our guide went above and beyond to show us around.',
    location: 'Singapore',
  },
  {
    name: 'Emily Watson',
    avatar: 'EW',
    rating: 5,
    date: 'November 2025',
    text: 'Boti Falls hike was challenging but rewarding! Swimming at the base of the falls was magical. Great insights about local plants and wildlife.',
    location: 'Melbourne, Australia',
  },
  {
    name: 'Olivia Adams',
    avatar: 'OA',
    rating: 5,
    date: 'October 2025',
    text: 'Jamestown walking tour was the highlight! Street art, lighthouse views, and food stops were perfectly curated. Felt like the real Accra.',
    location: 'New York, USA',
  },
  {
    name: 'Lucas Muller',
    avatar: 'LM',
    rating: 4,
    date: 'September 2025',
    text: 'Very educational Elmina Castle tour. Walking through the Door of No Return is unforgettable. The fishing village portion added a nice contrast.',
    location: 'Berlin, Germany',
  },
  {
    name: 'Aisha Patel',
    avatar: 'AP',
    rating: 5,
    date: 'August 2025',
    text: 'Lake Volta sunset cruise was pure magic! Golden sky, calm waters, and fresh seafood dinner. Perfect for couples or solo travellers.',
    location: 'Mumbai, India',
  },
  {
    name: 'Ryan O\'Brien',
    avatar: 'RO',
    rating: 5,
    date: 'July 2025',
    text: 'Fascinating Kumasi and Ashanti Kingdom tour. The craft villages and Kejetia Market were incredible. Ghanaian hospitality is unmatched!',
    location: 'Dublin, Ireland',
  },
  {
    name: 'Sophie Laurent',
    avatar: 'SL',
    rating: 5,
    date: 'June 2025',
    text: 'Ada Foah beach escape was exactly what I needed. Pristine beach, great food, and a bonus river cruise. Perfect way to unwind after touring.',
    location: 'Paris, France',
  },
]

export { recommendedTours, destinations, dayTours, multiDayTours, topRatedTours, sellOutTours, lastMinuteDeals, reviews }
